In [4]:
import numpy as np

In [ ]:
zero=np.array(46)
print(type(zero))

<class 'numpy.ndarray'>


In [ ]:
OneD=np.array([12,34,45,56,67,78,87])
OneD

array([12, 34, 45, 56, 67, 78, 87])

In [ ]:
TwoD=np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
TwoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14]])

In [ ]:
ThreeD=np.array([[[1,2,3,4],[4,5,6,7],[6,7,8,9]]])
ThreeD

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [6, 7, 8, 9]]])

In [ ]:
np.ndim(TwoD)

2

In [ ]:
np.size(TwoD)

12

In [ ]:
np.shape(TwoD)

(3, 4)

In [ ]:
print(len(OneD))

7


In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
np.arange(10,30,8)

array([10, 18, 26])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.linspace(1,25,15)

array([ 1.        ,  2.71428571,  4.42857143,  6.14285714,  7.85714286,
        9.57142857, 11.28571429, 13.        , 14.71428571, 16.42857143,
       18.14285714, 19.85714286, 21.57142857, 23.28571429, 25.        ])

In [6]:
np.linspace(4,50,5)

array([ 4. , 15.5, 27. , 38.5, 50. ])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
np.random.rand(4)

array([0.01371674, 0.03950569, 0.9428395 , 0.46713398])

In [8]:
np.random.rand(4,2,5)

array([[[0.86140095, 0.42549769, 0.11925094, 0.60136245, 0.36755302],
        [0.51204415, 0.32637199, 0.06363384, 0.57377186, 0.74722077]],

       [[0.28676756, 0.26321358, 0.04421081, 0.53890631, 0.50572413],
        [0.78564989, 0.38303542, 0.37802444, 0.06048488, 0.15600023]],

       [[0.46104414, 0.18559785, 0.34932116, 0.14967988, 0.98431787],
        [0.18792569, 0.67121173, 0.65264462, 0.50870481, 0.43213845]],

       [[0.86114679, 0.94738063, 0.65743898, 0.98874486, 0.19409236],
        [0.11437185, 0.7429755 , 0.3065798 , 0.32957043, 0.06234432]]])

In [10]:
np.random.randint(1,6,10)

array([2, 1, 3, 4, 4, 4, 3, 2, 4, 4])

In [12]:
b=np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [13]:
b.shape

(15,)

In [14]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [16]:
np.min(b)

np.int64(1)

In [17]:
np.max(b)

np.int64(29)

In [18]:
b.argmax()

np.int64(14)

In [21]:
b[0:6]

array([ 1,  3,  5,  7,  9, 11])

In [22]:
b[:5]

array([1, 3, 5, 7, 9])

In [23]:
b[3:]

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])